### ISSUE TITLE
Käyttäjä pystyy hakemaan article muotoisia viitteitä vapaasti

### ISSUE THREAD

**Issue by santeri0200** [santeri0200/FlashForge#32]
- [x] Add search field #34 
- [x] Add results page #35
    - [x] Add html template for the page
    - [x] Add route (to routes.py)
- [x] Add tests
    - [x] Add database tests #44 
        - [x] Add database call (to database.py) #37 
    - [x] Add robot tests #31 

Hyväksymiskriteeri: Yllämainitut taskit on suoritettu Definition of Done:n mukaan.
