### ISSUE TITLE
Käyttäjä pystyy muokkaamaan ja poistamaan viitteitä

### ISSUE THREAD

**Issue by santeri0200** [santeri0200/FlashForge#33]
- [x] Add editing and deletion capabilities to each referencepage #38
   - ~Blocked by #32~
- [x] Add tests
    - [x] Add database tests #41 
        - [x] Add database call (to database.py) #38 
    - [x] Add robot tests

Hyväksymiskriteeri: Yllämainitut taskit on suoritettu Definition of Done:n mukaan.
